PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS accounts(domain TEXT PRIMARY KEY,name TEXT,state TEXT,fit TEXT,source TEXT,observed_at TEXT,data_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS people(person_key TEXT PRIMARY KEY,email TEXT,profile TEXT,domain TEXT,name TEXT,title TEXT,state TEXT,source TEXT,observed_at TEXT,data_json TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS people_email ON people(email);
CREATE INDEX IF NOT EXISTS people_profile ON people(profile);
CREATE INDEX IF NOT EXISTS people_domain ON people(domain);
CREATE TABLE IF NOT EXISTS source_records(source TEXT,record_key TEXT,kind TEXT,data_json TEXT NOT NULL,digest TEXT NOT NULL,PRIMARY KEY(source,record_key));
CREATE TABLE IF NOT EXISTS attempts(idem_key TEXT PRIMARY KEY,channel TEXT,recipient TEXT,domain TEXT,sender TEXT,status TEXT,provider_id TEXT,at TEXT,payload_json TEXT NOT NULL,receipt_json TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS attempt_recipient ON attempts(channel,recipient);
CREATE TABLE IF NOT EXISTS suppressions(entity_type TEXT,value TEXT,reason TEXT,source TEXT,observed_at TEXT,data_json TEXT NOT NULL,PRIMARY KEY(entity_type,value,source,reason));
CREATE TABLE IF NOT EXISTS sender_consent(email TEXT PRIMARY KEY,daily_cap INTEGER,enabled INTEGER,source TEXT,data_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS budgets(provider TEXT,month TEXT,limit_credits REAL,reserved_credits REAL,data_json TEXT NOT NULL,PRIMARY KEY(provider,month));
CREATE TABLE IF NOT EXISTS actions(action_key TEXT PRIMARY KEY,channel TEXT,recipient TEXT,domain TEXT,sender TEXT,status TEXT,payload_json TEXT NOT NULL,at TEXT,reason TEXT);
CREATE TABLE IF NOT EXISTS events(event_id TEXT PRIMARY KEY,at TEXT,kind TEXT,entity TEXT,payload_json TEXT NOT NULL,source_digest TEXT);
CREATE INDEX IF NOT EXISTS event_time ON events(at);
CREATE TABLE IF NOT EXISTS bookings(booking_key TEXT PRIMARY KEY,recipient TEXT,domain TEXT,at TEXT,state TEXT,data_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS history(history_key TEXT PRIMARY KEY,recipient TEXT,domain TEXT,at TEXT,kind TEXT,data_json TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS history_recipient ON history(recipient);
CREATE TABLE IF NOT EXISTS signals(signal_key TEXT PRIMARY KEY,domain TEXT,kind TEXT,at TEXT,data_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS resources(resource_key TEXT PRIMARY KEY,kind TEXT,provider TEXT,provider_id TEXT,url TEXT,data_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS settings(name TEXT PRIMARY KEY,data_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sources(name TEXT PRIMARY KEY,record_count INTEGER,key_digest TEXT,data_digest TEXT,captured_at TEXT);
CREATE TABLE IF NOT EXISTS leases(name TEXT PRIMARY KEY,owner TEXT,expires_at REAL);
