const slides=[...document.querySelectorAll('.slide')],toc=document.getElementById('toc');let index=0;
function show(n){index=Math.max(0,Math.min(slides.length-1,n));slides.forEach((s,i)=>{s.hidden=i!==index;});slides[index].scrollTop=0;document.getElementById('slide-count').textContent=`${index+1} / ${slides.length}`;document.getElementById('chapter-label').textContent=`Section ${slides[index].dataset.chapter} of 5`;document.getElementById('prev').disabled=index===0;document.getElementById('next').disabled=index===slides.length-1;document.getElementById('progress-bar').style.width=`${(index+1)/slides.length*100}%`;history.replaceState(null,'','#'+slides[index].id);window.dispatchEvent(new CustomEvent('workshop-slide',{detail:slides[index].id}));}
function fromHash(){const n=slides.findIndex(s=>'#'+s.id===location.hash);show(n<0?0:n);}
document.getElementById('prev').addEventListener('click',()=>show(index-1));document.getElementById('next').addEventListener('click',()=>show(index+1));document.getElementById('contents').addEventListener('click',()=>toc.showModal());document.getElementById('close-contents').addEventListener('click',()=>toc.close());document.querySelectorAll('[data-index]').forEach(b=>b.addEventListener('click',()=>{show(Number(b.dataset.index));toc.close();}));
document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||e.altKey||e.ctrlKey||e.metaKey||e.shiftKey||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)||e.target.isContentEditable)return;if(e.key==='ArrowRight'||e.key==='PageDown'){e.preventDefault();show(index+1);}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();show(index-1);}if(e.key==='Home'){e.preventDefault();show(0);}if(e.key==='End'){e.preventDefault();show(slides.length-1);}});
document.getElementById('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{message('Use your browser’s fullscreen command.');}});
let timer;function message(s){const el=document.getElementById('copy-message');el.textContent=s;el.classList.add('visible');clearTimeout(timer);timer=setTimeout(()=>el.classList.remove('visible'),3500);}
document.querySelectorAll('[data-copy],[data-copy-text]').forEach(b=>b.addEventListener('click',async()=>{const text=b.dataset.copyText||document.getElementById(b.dataset.copy).value;try{await navigator.clipboard.writeText(text);message('Copied. Paste into your local Codex or Claude Code project.');window.GTMWorkshop?.celebrate('Prompt copied. Paste it into your local agent.');}catch{message('Select the full prompt and copy it.');}}));
window.addEventListener('hashchange',fromHash);fromHash();
const promptDialog=document.getElementById('prompt-dialog');let promptOpener;
document.querySelectorAll('[data-open-prompt]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();const source=document.getElementById('prompt-'+b.dataset.openPrompt);if(!source)return;promptOpener=b;document.getElementById('modal-prompt').value=source.value;const template=source.dataset.sourceTemplate||source.defaultValue;window.GTMWorkshop?.attachPrompt(document.getElementById('modal-prompt'),template);const fields=promptDialog.querySelector('.company-inputs');fields.hidden=!template.includes('[YOUR_COMPANY_WEBSITE]');document.getElementById('prompt-title').textContent=source.closest('.slide').querySelector('h1').textContent;promptDialog.showModal();promptDialog.querySelector('[data-close-dialog]').focus();}));
promptDialog.querySelector('[data-close-dialog]').addEventListener('click',()=>promptDialog.close());
promptDialog.addEventListener('close',()=>promptOpener?.focus());

// Pause the page preview and read the exact redacted email without leaving the deck.
document.querySelectorAll('[data-scroll-toggle]').forEach(b=>b.addEventListener('click',()=>{const preview=b.closest('.zuora-browser');const paused=preview.dataset.paused!=='true';preview.dataset.paused=String(paused);b.setAttribute('aria-pressed',String(paused));b.textContent=paused?'Resume scroll':'Pause scroll';}));
const zuoraEmailDialog=document.getElementById('zuora-email-dialog');let zuoraEmailOpener;
document.querySelectorAll('[data-open-email]').forEach(b=>b.addEventListener('click',()=>{zuoraEmailOpener=b;zuoraEmailDialog.showModal();zuoraEmailDialog.querySelector('[data-close-email]').focus();}));
zuoraEmailDialog?.querySelector('[data-close-email]').addEventListener('click',()=>zuoraEmailDialog.close());
zuoraEmailDialog?.addEventListener('close',()=>zuoraEmailOpener?.focus());
