from pathlib import Path
import argparse,html
p=argparse.ArgumentParser();p.add_argument('--output-dir',type=Path);p.add_argument('--hosted',action='store_true');args=p.parse_args()
r=Path(__file__).resolve().parents[1];out=args.output_dir or r
E=html.escape
prefix='' if args.hosted else 'https://metadata-gtm-workshops.vercel.app/gtm-part1/'
def video(key,title,poster,duration):
 return '<video class="workshop-video" id="'+key+'" controls playsinline preload="none" poster="'+prefix+'media/'+poster+'" aria-label="'+E(title)+'"><source src="'+prefix+'media/'+key+'.mp4" type="video/mp4">Open the workshop site to watch this recording.</video><p class="media-caption" data-video-note="'+key+'">'+duration+' · <a href="https://metadata-gtm-workshops.vercel.app/gtm-part1/Recordings.html#'+key+'">Watch on the password-protected workshop site</a></p>'
jumps=[(365,'06:05','Clone the project'),(673,'11:13','Company brief and setup'),(1039,'17:19','Research the targets'),(1309,'21:49','Build the first page'),(1518,'25:18','Review the page'),(2005,'33:25','Save the skill'),(2190,'36:30','Reuse it for Okta'),(2719,'45:19','Check the saved files')]
buttons=''.join('<button data-jump="'+str(t)+'" data-video="part1-walkthrough"><span>'+time+'</span>'+title+'</button>' for t,time,title in jumps)
body='''<p class="eyebrow">Part 1 · Recorded build</p><h1>Watch the work.<br>Then build your own.</h1><p class="recordings-intro">Follow the full recorded replay, or jump to the task you need. The two short Zoom clips show Gil explaining the same steps during his rehearsal.</p><div class="local-status"><strong>Local and unpublished.</strong><span>Part 1 creates pages on your computer. Publishing is not required.</span></div>
<article class="recording-card" id="full-replay"><p class="eyebrow">Full recorded replay · October 8, 2026</p><h2>Two account pages. One reused skill.</h2><p>The replay uses Metadata’s company context with Zuora and Okta as targets. It includes setup, a failed attempt, repairs, page checks and skill reuse.</p><div class="recording-meta"><span>54:51 · Silent screen recording · Normal speed</span><span>All recorded steps retained</span></div>'''+video('part1-walkthrough','Full Part 1 recorded build','part1-walkthrough.jpg','54:51')+'''<div class="recording-jumps">'''+buttons+'''</div><p class="media-caption">Jump times are approximate prompt-submission times. The replay uses local Codex through a browser test console. That console is not the Codex desktop app.</p><div class="recording-proof"><div><strong>2 reviewed pages</strong><small>Zuora and Okta. Local files.</small></div><div><strong>1 reused skill</strong><small>Read in a fresh agent session.</small></div><div><strong>15 checks passed</strong><small>Recorded verification, October 8.</small></div></div><p class="media-caption">This verifies the local Part 1 workflow. It does not test a beginner’s setup, live outreach or the full production GTM engine.</p><p class="media-caption">The recorded checkpoint uses an earlier prompt. Use the current checkpoint: unpublished pages are expected, and email setup belongs to Part 2.</p></article>
<div class="recording-grid"><article class="recording-card" id="gil-first-page"><p class="eyebrow">Gil’s Zoom rehearsal · October 7</p><h2>Open the first page.</h2><p>Gil opens a local Bedtime Magic page for Metadata, then checks the next-step button. The clip begins on the prompt and switches to the page.</p>'''+video('gil-open-first-page','Gil opens his first page','gil-open-first-page.jpg','0:55 · Original rehearsal audio')+'''<p class="media-caption">This rehearsal uses an earlier prompt layout. Use the complete prompts in the current slides and booklet.</p><a href="Part-1-Presentation.html#p1-build-page">Go to the first-page exercise</a></article><article class="recording-card" id="gil-skill"><p class="eyebrow">Gil’s Zoom rehearsal · October 7</p><h2>Save the instructions.</h2><p>Gil explains saving the page method as a skill and using it for the next target. The clip shows the prompt, not an agent execution.</p>'''+video('gil-save-the-skill','Gil explains saving the skill','gil-save-the-skill.jpg','0:14 · Original rehearsal audio')+'''<p class="media-caption">To see the saved skill run, use the full replay’s “Reuse it for Okta” jump.</p><a href="Part-1-Presentation.html#p1-save-skill">Go to the skill exercise</a></article></div>
<details class="recording-card"><summary>Watch the separate phone-layout check · 21:45</summary><p>The mobile-browser recording checks the same generated pages at 390 × 844. Silent, normal speed.</p>'''+video('phone-layout-checks','Phone layout checks','phone-layout-checks.jpg','21:45')+'''</details><section class="package-band recording-band"><div><h3>Keep building in the booklet.</h3><p>Copy one complete prompt. Run it in your local Codex or Claude Code project. Check the result before moving on.</p></div><a class="button" href="Participant-Booklet.html">Return to the booklet</a></section>'''
js='''document.querySelectorAll('[data-jump]').forEach(b=>b.addEventListener('click',()=>{const v=document.getElementById(b.dataset.video),t=Number(b.dataset.jump);const seek=()=>{v.currentTime=t;v.play().catch(()=>{});};if(v.readyState>=1)seek();else{v.addEventListener('loadedmetadata',seek,{once:true});v.load();}v.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}));document.querySelectorAll('video').forEach(v=>{v.addEventListener('play',()=>document.querySelectorAll('video').forEach(o=>{if(o!==v)o.pause();}));v.addEventListener('error',()=>{const n=document.querySelector('[data-video-note="'+v.id+'"]');n.classList.add('media-error');n.prepend('If the player cannot load, sign in to the workshop site. ');});});'''
brand='/gtm-part1/' if args.hosted else 'START-HERE.html'
out.joinpath('Recordings.html').write_text('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Recorded Part 1 build | Metadata</title><link rel="stylesheet" href="site.css"><link rel="stylesheet" href="media.css"><link rel="icon" href="assets/metadata-icon.jpeg"></head><body><header class="nav"><a class="brand" href="'+brand+'">metadata<span>.</span></a><nav class="nav-links"><a href="Participant-Booklet.html">Booklet</a><a href="Part-1-Presentation.html">Slides</a><a href="'+brand+'">Welcome</a></nav></header><main class="recordings-main">'+body+'</main><script>'+js+'</script></body></html>')
print('Recording page built. Video binaries remain outside the public repository.')
